// Generated by: supabase gen types typescript --local > src/lib/supabase/database.types.ts
// Run this command after `supabase start` with local migrations applied.
// This file is dev tooling only — not imported at runtime by the orchestrator.

export type Json = string | number | boolean | null | { [key: string]: Json | undefined } | Json[];

export interface Database {
  public: {
    Tables: {
      contacts: {
        Row: {
          id: string;
          phone: string;
          status: 'prospecto' | 'cliente' | 'inactivo';
          channel_origin: 'whatsapp' | 'voice';
          opted_in_at: string;
          name: string | null;
          email: string | null;
          summary: string | null;
          summary_updated_at: string | null;
          summary_version: number;
          pending_turns: number;
          deleted_at: string | null;
          created_at: string;
          updated_at: string;
        };
        Insert: Omit<Database['public']['Tables']['contacts']['Row'], 'id' | 'opted_in_at' | 'created_at' | 'updated_at' | 'pending_turns'> & Partial<Pick<Database['public']['Tables']['contacts']['Row'], 'id' | 'opted_in_at' | 'created_at' | 'updated_at' | 'pending_turns'>>;
        Update: Partial<Database['public']['Tables']['contacts']['Row']>;
      };
      conversations: {
        Row: {
          id: string;
          contact_id: string;
          channel: 'whatsapp' | 'voice';
          status: 'open' | 'closed';
          current_intent: string | null;
          started_at: string;
          last_turn_at: string;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['conversations']['Row'], 'id' | 'started_at' | 'last_turn_at' | 'created_at'> & Partial<Pick<Database['public']['Tables']['conversations']['Row'], 'id' | 'started_at' | 'last_turn_at' | 'created_at'>>;
        Update: Partial<Database['public']['Tables']['conversations']['Row']>;
      };
      messages: {
        Row: {
          id: string;
          conversation_id: string;
          contact_id: string;
          direction: 'inbound' | 'outbound';
          content: string;
          in_reply_to: string | null;
          metadata: Json | null;
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at'> & Partial<Pick<Database['public']['Tables']['messages']['Row'], 'id' | 'created_at'>>;
        Update: Partial<Database['public']['Tables']['messages']['Row']>;
      };
      message_embeddings: {
        Row: {
          id: string;
          message_id: string;
          contact_id: string;
          embedding: number[];
          status: 'pending' | 'indexed';
          created_at: string;
        };
        Insert: Omit<Database['public']['Tables']['message_embeddings']['Row'], 'id' | 'created_at'> & Partial<Pick<Database['public']['Tables']['message_embeddings']['Row'], 'id' | 'created_at'>>;
        Update: Partial<Database['public']['Tables']['message_embeddings']['Row']>;
      };
      audit_log: {
        Row: {
          id: string;
          occurred_at: string;
          actor: string;
          action: string;
          entity_type: string;
          entity_id: string | null;
          payload: Json | null;
        };
        Insert: Omit<Database['public']['Tables']['audit_log']['Row'], 'id' | 'occurred_at'> & Partial<Pick<Database['public']['Tables']['audit_log']['Row'], 'id' | 'occurred_at'>>;
        Update: never;
      };
    };
    Functions: {
      write_audit_log: {
        Args: { p_actor: string; p_action: string; p_entity_type: string; p_entity_id: string; p_payload?: Json };
        Returns: void;
      };
      search_contact_memory: {
        Args: { p_contact_id: string; p_query_embedding: number[]; p_limit?: number };
        Returns: { message_id: string; contact_id: string; content: string; similarity: number; created_at: string }[];
      };
    };
  };
}
