import { z, defineConfig } from "@botpress/runtime";
import {
  DEFAULT_DEVELOPMENT_EMULATOR_PHONE_E164,
  E164_PATTERN,
} from "./src/channels/shared/emulator-envelope";

export default defineConfig({
  name: "Studyx",
  description:
    "StudyX sales conversation adapter. Next.js and Supabase remain the source of truth.",

  configuration: {
    schema: z.object({
      apiBaseUrl: z.string().min(1).default("http://localhost:3000"),
      orchestratorKeyId: z.string().min(1).default("botpress-dev"),
      requestTimeoutMs: z.number().int().min(1000).max(30000).default(8000),
      retryBaseDelayMs: z.number().int().min(10).max(5000).default(250),
      retryMaxDelayMs: z.number().int().min(100).max(10000).default(2000),
      emulatorPhoneE164: z
        .string()
        .regex(E164_PATTERN, "emulatorPhoneE164 must be a strict E.164 identity")
        .default(DEFAULT_DEVELOPMENT_EMULATOR_PHONE_E164),
      automationEnabled: z.boolean().default(false),
    }),
  },

  secrets: {
    STUDYX_ORCHESTRATOR_KEY: {
      description: "Shared credential presented to the StudyX Next.js API.",
    },
    STUDYX_SIGNING_SECRET: {
      description: "HMAC-SHA256 key used to sign StudyX API requests.",
    },
    GEMINI_API_KEY: {
      description:
        "Google AI Studio key used by transcribeAudio (Phase 4). Model: gemini-2.5-flash.",
    },
    TELEGRAM_BOT_A_TOKEN: {
      description:
        "Telegram Bot API token for the sandbox Bot A (Phase 2). Used to download voice notes for transcription.",
    },
  },

  bot: {
    state: z.object({
      schemaVersion: z.number().int().default(1),
    }),
  },

  user: {
    state: z.object({}),
  },

  conversation: {
    tags: {
      // The ADK runtime persists these on every turn (auto title + lifecycle
      // status). Without the declaration the API rejects them and every turn
      // logs "Failed to persist tags" — declaring them is the fix, not a
      // feature: our own code never reads or writes them.
      title: {
        title: "Conversation title",
        description: "Auto-generated by the Botpress runtime.",
      },
      status: {
        title: "Conversation status",
        description: "Lifecycle status maintained by the Botpress runtime.",
      },
    },
  },

  message: {
    tags: {
      studyxOutboundId: {
        title: "StudyX outbound ID",
        description:
          "Stable outbound identifier committed by StudyX and attached to the Botpress message.",
      },
      studyxTraceId: {
        title: "StudyX trace ID",
        description: "End-to-end correlation ID without customer content.",
      },
    },
  },

  evals: {
    idleTimeout: 60000,
    judgePassThreshold: 4,
  },
});
