-- GENERATED BY scripts/generate-studyx-manual-seed.mjs — DO NOT EDIT.
-- Canonical source: MANUAL CAPACITACION STUDYX 1.docx.pdf
-- SHA-256: 47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1
-- The 40 explicitly catalogued courses become active. Existing courses that
-- are absent from the manual are made inactive, never deleted.

BEGIN;
SET search_path TO public;

UPDATE workspaces
SET metadata = COALESCE(metadata, '{}'::jsonb) || '{"catalog_source":"studyx_manual_1","catalog_source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","catalog_source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","catalog_active_count":40,"catalog_verified_at":"2026-08-23"}'::jsonb,
updated_at = now()
WHERE id = 'b0000000-0000-4000-8000-000000000001'::uuid;

INSERT INTO offerings (
  id, workspace_id, code, display_name, offering_type, status, description,
  value_proposition, price_type, price_amount, currency, billing_interval,
  audience, delivery, guardrails, metadata
) VALUES
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'vino_cata_maridaje',
    'Introducción al Vino, la Cata y el Maridaje', 'course', 'active', 'Academia Gastronómica. 19 clases. En este curso orientamos el aprendizaje a conocer la elaboración de los vinos tintos, blancos, rosados y algunos especiales como espumosos y dulces.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":19,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":9,"academy":"Academia Gastronómica","declared_classes":19,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'introduccion_catering',
    'Introducción al Catering', 'course', 'active', 'Academia Gastronómica. 20 clases. En este curso analizamos las diferentes opciones, adecuadas a todo tipo de público, las necesidades de alimentos y bebidas según el evento y los menús adaptados para cada ocasión.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":20,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":9,"academy":"Academia Gastronómica","declared_classes":20,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'sushi_principiantes',
    'Sushi para Principiantes', 'course', 'active', 'Academia Gastronómica. 10 clases. Este curso está diseñado para que los alumnos aprendan todo lo necesario sobre el mundo del sushi, el paso a paso de recetas únicas, con más de 120 piezas diferentes para ser un verdadero sushi man cuenta también con la enseñanza de otras comidas y postres japoneses.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":10,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":8,"academy":"Academia Gastronómica","declared_classes":10,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'entrenamiento_funcional',
    'Entrenamiento Funcional', 'course', 'active', 'Academia de Salud y Bienestar. 16 clases. El curso está diseñado para empezar desde cero, cualquier persona puede realizarlo sin límites de edad ni de ningún otro tipo de limitación.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":16,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":9,"academy":"Academia de Salud y Bienestar","declared_classes":16,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'nutricion_alimentacion',
    'Nutrición y Alimentación Saludable', 'course', 'active', 'Academia de Salud y Bienestar. 16 clases. El objetivo de realizar este curso es que se lleven los alumnos una enseñanza y aprendizaje correcto de lo que es una buena alimentación, para eso vamos a ir viendo temas con respecto a la nutrición, qué nos van a ayudar a tener herramientas para saber lo que es realmente una alimentación saludable.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":16,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":9,"academy":"Academia de Salud y Bienestar","declared_classes":16,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'marketing_digital',
    'Marketing Digital', 'course', 'active', 'Academia de Marketing. 16 clases. En este diplomado lograremos desarrollar estrategias exitosas para comunicar de forma eficaz y potenciar tu negocio.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":16,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":10,"academy":"Academia de Marketing","declared_classes":16,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'community_manager',
    'Community Manager', 'course', 'active', 'Academia de Marketing. 16 clases. Aprenderemos a manejar, optimizar y administrar de forma profesional tus redes sociales: crear estrategias de Social Media, hacer campañas digitales, actuar en una crisis y medir el éxito de tu negocio online.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":16,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":10,"academy":"Academia de Marketing","declared_classes":16,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'especialista_marketing',
    'Especialista en Marketing', 'course', 'active', 'Academia de Marketing. 17 clases. Al aprender marketing podrás analizar los mercados, mejorar la distribución y logística de tu emprendimiento, crear una campaña de publicidad y comunicación, posicionar tu marca y entender cuáles son las necesidades de tus clientes.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":17,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":10,"academy":"Academia de Marketing","declared_classes":17,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'introduccion_ecommerce',
    'Introducción al Ecommerce', 'course', 'active', 'Academia de Marketing. 8 clases. En este diplomado brindaremos todas las herramientas necesarias para vender productos en internet, comenzando desde los fundamentos básicos, pasando por el desarrollo de un plan de acción con objetivos.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":8,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":10,"academy":"Academia de Marketing","declared_classes":8,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'fotografia_celulares_tiendas_online',
    'Fotografía con Celulares para Tiendas Online', 'course', 'active', 'Academia de Marketing. 20 clases. En este curso vamos a ver cómo aprovechar al máximo la cámara de nuestro celular, técnicas de iluminación, conceptos de fotografía y exposición, edición y retoque de los productos, creación de videos promocionales y cómo aplicar todo a nuestra red social preferida para el impulso de nuestro negocio.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":20,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":11,"academy":"Academia de Marketing","declared_classes":20,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'influencers_creadores_contenidos',
    'Influencers y Creadores de Contenidos', 'course', 'active', 'Academia de Marketing. 20 clases. En este diplomado veremos y te enseñaremos cómo lograr y crear tu propia comunidad, sobre temas que te gusten y apasionen, con contenidos originales y gran empatía en las diferentes redes sociales, logrando interactuar y estrechar lazos con los seguidores para poder convertirte en un verdadero influencer.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":20,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":11,"academy":"Academia de Marketing","declared_classes":20,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'publicidad_redes_sociales',
    'Publicidad en Redes Sociales', 'course', 'active', 'Academia de Marketing. 10 clases. Con este curso aprenderemos a hacer publicidad en Facebook e instagram y generar anuncios de forma eficiente en plataformas para público específico como twitter y linkedln.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":10,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":11,"academy":"Academia de Marketing","aliases":["publicidad redes","publicidad en redes"],"declared_classes":10,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'maquillaje_profesional',
    'Maquillaje Profesional', 'course', 'active', 'Academia de Moda y Belleza. 38 clases. El curso plantea como meta específica lograr conocimientos para trabajar como maquillador profesional, reconociendo los materiales de trabajo, tipo de pieles, forma de rostros, gustos del cliente y asesoramientos necesarios en cada trabajo.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":38,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":11,"academy":"Academia de Moda y Belleza","declared_classes":38,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'unas_gelificadas',
    'Uñas Gelificadas', 'course', 'active', 'Academia de Moda y Belleza. 25 clases. Incorporar conocimientos y habilidades propias de la construcción de uñas en gel en las manos.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":25,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"academy":"Academia de Moda y Belleza","declared_classes":25,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'camaras_seguridad',
    'Instalación y Configuración de Cámaras de Seguridad', 'course', 'active', 'Academia de Oficios. 12 clases. En este diplomado le brindaremos a los participantes los conocimientos necesarios y técnicos, para la instalación y configuración de Cámaras de Seguridad en comercios, casas, galpones o empresas, permitiendo visualizarlas en diferentes componentes (TV, PC y/o Celulares).',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":12,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"academy":"Academia de Oficios","declared_classes":12,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'aires_acondicionados',
    'Instalación de Aires Acondicionados', 'course', 'active', 'Academia de Oficios. 9 clases. El propósito del curso de instalador es el de instruir a todas las personas a que puedan emprender las tareas de instalación y puesta en marcha de equipos de Aire Acondicionado.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":9,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"academy":"Academia de Oficios","declared_classes":9,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'energia_solar_fotovoltaica',
    'Energía Solar Fotovoltaica', 'course', 'active', 'Academia de Oficios. 8 clases. Conocer el componente más importante en las instalaciones fotovoltaicas, los módulos fotovoltaicos, únicos dispositivos capaces de convertir directamente la energía luminosa procedente del sol en energía eléctrica continua e introducirnos en la energía solar fotovoltaica, que es la transformación de la luz solar en energía.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":8,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"academy":"Academia de Oficios","declared_classes":8,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'armado_reparacion_pc',
    'Armado y Reparación de PC', 'course', 'active', 'Academia de Oficios. 22 clases. Este curso abarca el mantenimiento de computadoras de escritorio desde cero con casos reales otorgando las herramientas necesarias para que el futuro técnico sepa cuándo reparar y cuándo reemplazar los componentes dañados como también asesorar a sus clientes con las mejores soluciones a su equipamiento.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":22,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"academy":"Academia de Oficios","declared_classes":22,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'reparacion_celulares',
    'Reparación de Celulares', 'course', 'active', 'Academia de Oficios. 20 clases. Los objetivos de este curso son: lograr que el alumno conozca la evolución de la telefonía celular, hasta el desarrollo total de los Smartphone que tenemos en la actualidad, saber manipular distintas herramientas de medición, adquirir el conocimiento para poder realizar distintas reparaciones (tales como cambios de módulos, reparación de pines y de integra',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":20,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"academy":"Academia de Oficios","aliases":["reparar celu","reparar celulares","arreglo de celulares"],"declared_classes":20,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'redes_informaticas',
    'Redes Informáticas', 'course', 'active', 'Academia de Oficios. 16 clases. Este curso te permitirá conocer el funcionamiento de las redes informáticas, y cada uno de los elementos y dispositivos que la componen.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":16,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"academy":"Academia de Oficios","declared_classes":16,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'decoracion_de_interiores',
    'Decoración de Interiores', 'course', 'active', 'Academia de Emprendedores. 33 clases. Este curso invita a los participantes a formarse en el oficio de Decorador de Interiores, aprendiendo sus primeros pasos en el mundo del diseño y la decoración.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":33,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"academy":"Academia de Emprendedores","declared_classes":33,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'fotografia_profesional',
    'Fotografía Profesional', 'course', 'active', 'Academia de Emprendedores. 41 clases. Este curso está apuntado a todo aquel que quiera conocer desde cero el proceso fotográfico actual, con esto nos referimos al digital.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":41,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"academy":"Academia de Emprendedores","declared_classes":41,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'organizador_eventos_sociales',
    'Organizador Profesional de Eventos Sociales', 'course', 'active', 'Academia de Emprendedores. 20 clases. Durante estas clases virtuales, aprenderás conceptos, términos del rubro de eventos, para aplicar en el armado y desarrollo de tu empresa de eventos.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":20,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"academy":"Academia de Emprendedores","declared_classes":20,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'organizacion_baby_shower',
    'Organización de Baby Shower', 'course', 'active', 'Academia de Emprendedores. 21 clases. Celebrar la vida es parte de la magia de un Organizador de Eventos de Baby Shower, trabajar en un momento tan especial como la dulce espera de un bebé es un momento de emociones para la familia como para todo el personal que trabaja en el evento.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":21,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"academy":"Academia de Emprendedores","declared_classes":21,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'paisajismo_jardineria',
    'Paisajismo y Jardinería', 'course', 'active', 'Academia de Emprendedores. 23 clases. El curso tiene como objetivo brindar al alumno todas las variedades que se le pueden presentar en el momento de intervenir en un paisaje natural, capacitarlo en el estudio y el reconocimiento del espacio exterior tales como jardines delanteros, traseros, terrazas, balcones y en el ámbito público en parques y plazas, aprendiendo a analizar los compone',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":23,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"academy":"Academia de Emprendedores","declared_classes":23,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'estrategias_emprender',
    'Estrategias para Emprender', 'course', 'active', 'Academia de Emprendedores. 20 clases. En este curso proponemos claves fundamentales para emprender un negocio con éxito, a través de estrategias efectivas para no fallar en el intento.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":20,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"academy":"Academia de Emprendedores","declared_classes":20,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'instagram_emprendedores',
    'Instagram para Emprendedores', 'course', 'active', 'Academia de Emprendedores. 10 clases. El curso está pensado para que los emprendedores puedan desarrollar sus negocios y consigan mayor visibilidad.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":10,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"academy":"Academia de Emprendedores","declared_classes":10,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'diseno_corel_draw',
    'Diseño Gráfico con Corel Draw', 'course', 'active', 'Academia de Diseño Informático. 16 clases. Es sumamente necesario entender la tarea de un diseñador gráfico y con el profesionalismo que debemos encarar nuestro trabajo para poder hacerlo de la mejor manera.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":16,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"academy":"Academia de Diseño Informático","declared_classes":16,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'diseno_photoshop',
    'Diseño Gráfico con Photoshop', 'course', 'active', 'Academia de Diseño Informático. 16 clases. Este diplomado cuenta con 16 clases, 8 ejercicios y 1 examen final.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":16,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"academy":"Academia de Diseño Informático","declared_classes":16,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'diseno_illustrator',
    'Diseño Gráfico con Illustrator', 'course', 'active', 'Academia de Diseño Informático. 17 clases. Este diplomado cuenta con 17 clases, 17 ejercicios, 6 exámenes parciales y 1 examen final.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":17,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"academy":"Academia de Diseño Informático","aliases":["Illustrator","curso de Illustrator"],"declared_classes":17,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'autocad_interiores',
    'AutoCAD orientado al Diseño de Interiores', 'course', 'active', 'Academia de Diseño Informático. 11 clases. En este Curso de AutoCAD vamos a adquirir el conocimiento práctico y teórico para dominar las técnicas de dibujo en forma digital y realizar planos técnicos en dos dimensiones.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":11,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"academy":"Academia de Diseño Informático","aliases":["AutoCAD","curso de AutoCAD"],"declared_classes":11,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'excel_integral',
    'Excel Integral', 'course', 'active', 'Academia de Negocios. 17 clases. Recomendamos este curso, con el que aprenderá las herramientas elementales, diferente tipos de fórmulas y funciones, gráficos, resúmenes de información, entre otras tantas actividades que puede realizar con este programa.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":17,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"academy":"Academia de Negocios","declared_classes":17,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'especialista_ventas',
    'Especialista en Ventas', 'course', 'active', 'Academia de Negocios. 16 clases. A través de este curso obtendrás todas las aptitudes necesarias para poder optimizar tus recursos y potenciar tus ventas.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":16,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"academy":"Academia de Negocios","declared_classes":16,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'coaching_liderazgo',
    'Coaching y Liderazgo', 'course', 'active', 'Academia de Negocios. 16 clases. En este curso permitiremos desarrollar actitudes, capacidades y habilidades que posibiliten enfrentar adecuadamente los desafíos del mercado laboral, en especial a nivel gerencial.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":16,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"academy":"Academia de Negocios","declared_classes":16,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'comunicacion_interna_empresas',
    'Comunicación Interna en Empresas', 'course', 'active', 'Academia de Negocios. 20 clases. En este curso, brindaremos las estrategias necesarias para gestionar e integrar adecuadamente un equipo humano de una empresa.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":20,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"academy":"Academia de Negocios","declared_classes":20,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'introduccion_criptomonedas',
    'Introducción a las Criptomonedas', 'course', 'active', 'Academia de Negocios. 21 clases. El objetivo de este curso es lograr que el alumno se familiarice con los conceptos básicos del mundo de las criptomonedas.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":21,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"academy":"Academia de Negocios","declared_classes":21,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'oratoria',
    'Oratoria', 'course', 'active', 'Academia Cultural. 20 clases. En este curso, analizaremos las claves de la oratoria, facilitando herramientas esenciales para lograr buenos resultados comunicaciones y alcanzar un feedback sin ruidos ni complicaciones con los interlocutores.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":20,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":16,"academy":"Academia Cultural","declared_classes":20,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'ingles_1',
    'Inglés 1', 'course', 'active', 'Academia Cultural. 12 clases. El objetivo de este curso es que el alumno adquiera conocimientos de inglés que perduren en el tiempo a través del aprendizaje y la lectura de materiales teóricos que pueda aplicar y apropiar en la práctica.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":12,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":16,"academy":"Academia Cultural","declared_classes":12,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'ingles_2',
    'Inglés 2', 'course', 'active', 'Academia Cultural. 12 clases. En este diplomado el alumno se adentrará en los modos, en cómo entablar una conversación y podrá aplicar todo lo aprendido.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":12,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":16,"academy":"Academia Cultural","declared_classes":12,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'ingles_3',
    'Inglés 3', 'course', 'active', 'Academia Cultural. 21 clases. En este diplomado el alumno adquirirá conocimientos sobre gramática y vocabulario que le dará las herramientas necesarias para poder desenvolverse en los distintos contextos presentados en el curso, tales como en el aeropuerto, en una entrevista laboral, etc.',
    NULL, 'fixed', 360.00, 'USD', 'custom',
    '{"language":"Spanish"}'::jsonb,
    '{"modality":"online","classes":21,"source":"MANUAL CAPACITACION STUDYX 1.docx.pdf"}'::jsonb,
    '{"never_invent_price":true,"forbidden_promises":["certificación verificada","título oficial","homologación","matrícula profesional","salida laboral garantizada","horarios de clases en vivo","política de devoluciones"]}'::jsonb,
    '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":16,"academy":"Academia Cultural","declared_classes":21,"total_price_usd":360,"payment_options_owner_confirmed":true,"price_source":"owner-confirmed 2026-08-20"}'::jsonb
  )
ON CONFLICT (workspace_id, code) DO UPDATE SET
  display_name = EXCLUDED.display_name,
  offering_type = EXCLUDED.offering_type,
  status = EXCLUDED.status,
  description = EXCLUDED.description,
  value_proposition = EXCLUDED.value_proposition,
  price_type = EXCLUDED.price_type,
  price_amount = EXCLUDED.price_amount,
  currency = EXCLUDED.currency,
  billing_interval = EXCLUDED.billing_interval,
  audience = EXCLUDED.audience,
  delivery = EXCLUDED.delivery,
  guardrails = EXCLUDED.guardrails,
  metadata = EXCLUDED.metadata,
  updated_at = now();

UPDATE offerings
SET status = 'inactive',
    metadata = COALESCE(metadata, '{}'::jsonb) || jsonb_build_object(
      'deactivated_by_catalog_sync', 'studyx_manual_1',
      'deactivated_at', now()
    ),
    updated_at = now()
WHERE workspace_id = 'b0000000-0000-4000-8000-000000000001'::uuid
  AND code NOT IN ('vino_cata_maridaje', 'introduccion_catering', 'sushi_principiantes', 'entrenamiento_funcional', 'nutricion_alimentacion', 'marketing_digital', 'community_manager', 'especialista_marketing', 'introduccion_ecommerce', 'fotografia_celulares_tiendas_online', 'influencers_creadores_contenidos', 'publicidad_redes_sociales', 'maquillaje_profesional', 'unas_gelificadas', 'camaras_seguridad', 'aires_acondicionados', 'energia_solar_fotovoltaica', 'armado_reparacion_pc', 'reparacion_celulares', 'redes_informaticas', 'decoracion_de_interiores', 'fotografia_profesional', 'organizador_eventos_sociales', 'organizacion_baby_shower', 'paisajismo_jardineria', 'estrategias_emprender', 'instagram_emprendedores', 'diseno_corel_draw', 'diseno_photoshop', 'diseno_illustrator', 'autocad_interiores', 'excel_integral', 'especialista_ventas', 'coaching_liderazgo', 'comunicacion_interna_empresas', 'introduccion_criptomonedas', 'oratoria', 'ingles_1', 'ingles_2', 'ingles_3')
  AND status = 'active';

-- Retire website-derived course sources so retrieval has one catalog truth.
UPDATE knowledge_sources
SET status = 'archived', updated_at = now()
WHERE workspace_id = 'b0000000-0000-4000-8000-000000000001'::uuid
  AND source_type = 'offering'
  AND COALESCE(metadata ->> 'canonical_source', '') <> 'studyx_manual_1'
  AND status <> 'archived';

-- Retire general statements that conflict with the owner-declared manual.
UPDATE knowledge_sources
SET status = 'archived', updated_at = now()
WHERE workspace_id = 'b0000000-0000-4000-8000-000000000001'::uuid
  AND title IN (
    'Qué vende StudyX',
    'Tamaño real del catálogo y qué no afirmar',
    'Modalidad: qué se puede afirmar sobre las clases'
  )
  AND status <> 'archived';

INSERT INTO knowledge_sources (
  id, workspace_id, source_type, title, content, status, version, metadata
) VALUES
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Introducción al Vino, la Cata y el Maridaje', 'Curso: Introducción al Vino, la Cata y el Maridaje.
Academia: Academia Gastronómica.
Cantidad informada por el manual: 19 clases.
En este curso orientamos el aprendizaje a conocer la elaboración de los vinos tintos, blancos, rosados y algunos especiales como espumosos y dulces. Determinar el origen, la variedad, antigüedad, elaboración y otras características de las diferentes variedades de vinos, conocer también los diferentes maridajes para que resulte exitosa la combinación entre la comida y la bebida. Los puntos más importantes que veremos son: Elaboración de los vinos en diferentes partes del mundo, la degustación, como diferenciarlos por color, aroma, sabor. Los diferentes tipos de vinos, de uvas, variedad de maridajes acorde al vino que se elija. Cuenta con 19 clases, 6 ejercicios y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":9,"course_code":"vino_cata_maridaje","academy":"Academia Gastronómica","declared_classes":19}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Introducción al Catering', 'Curso: Introducción al Catering.
Academia: Academia Gastronómica.
Cantidad informada por el manual: 20 clases.
En este curso analizamos las diferentes opciones, adecuadas a todo tipo de público, las necesidades de alimentos y bebidas según el evento y los menús adaptados para cada ocasión. Nos centramos en la organización del servicio, la planificación de los presupuestos y el cálculo de bebidas para reuniones sociales. Los puntos más importantes que veremos son: El armado del propio emprendimiento con los conceptos básicos sobre el catering, la importancia del menú, como se debe planificar, los diferentes tipos de catering que se pueden ofrecer a los clientes, como promocionar nuestro negocio, ideas de maridaje para nuestro catering y como sacar presupuestos a la hora de ofrecer el servicio. Se compone de 20 clases y 1 examen final',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":9,"course_code":"introduccion_catering","academy":"Academia Gastronómica","declared_classes":20}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Sushi para Principiantes', 'Curso: Sushi para Principiantes.
Academia: Academia Gastronómica.
Cantidad informada por el manual: 10 clases.
Este curso está diseñado para que los alumnos aprendan todo lo necesario sobre el mundo del sushi, el paso a paso de recetas únicas, con más de 120 piezas diferentes para ser un verdadero sushi man cuenta también con la enseñanza de otras comidas y postres japoneses. Los puntos más importantes que veremos son: Las herramientas necesarias para la elaboración correcta del sushi, el arroz que se debe utilizar y la cocción justa, técnicas de enrollado, recetario de sushi y de otras comidas y postres japoneses. Se compone de 10 clases, 4 exámenes parciales y 1 examen final',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":8,"course_code":"sushi_principiantes","academy":"Academia Gastronómica","declared_classes":10}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Entrenamiento Funcional', 'Curso: Entrenamiento Funcional.
Academia: Academia de Salud y Bienestar.
Cantidad informada por el manual: 16 clases.
El curso está diseñado para empezar desde cero, cualquier persona puede realizarlo sin límites de edad ni de ningún otro tipo de limitación. Aquí encontrarán todos los conceptos necesarios para un abordaje completo de la actividad, desde anatomía, fisiología, ejercitaciones, variantes, preparación de clases, rutinas y mucho más, porque sabemos que lo más importante para un profesor es el conocimiento, si puedes entenderlo vas a poder explicarlo. Los puntos más importantes que veremos son: Se divide en 3 módulos en los cuales veremos en primer lugar beneficios de este tipo de entrenamiento, la anatomía del cuerpo, las articulaciones y la importancia de cuidarlas a la hora de ejercitarse y las función de los huesos y cuál es la forma de no dañarlos. En el módulo número 2 veremos el sistema muscular, los tipos de músculos, su función, la importancia de la frecuencia cardiaca, los ejercicios para ejercitar a cada uno de los músculos, series, repeticiones, descansos y distintos circuitos y por último en el módulo número 3 veremos la importancia de la entrada en calor, las diferentes partes del cuerpo que trabajan al ejercitarse, coordinación y cómo planificar una clase. Cuenta con 16 clases, 8 exámenes parciales y 1 examen parcial',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":9,"course_code":"entrenamiento_funcional","academy":"Academia de Salud y Bienestar","declared_classes":16}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Nutrición y Alimentación Saludable', 'Curso: Nutrición y Alimentación Saludable.
Academia: Academia de Salud y Bienestar.
Cantidad informada por el manual: 16 clases.
El objetivo de realizar este curso es que se lleven los alumnos una enseñanza y aprendizaje correcto de lo que es una buena alimentación, para eso vamos a ir viendo temas con respecto a la nutrición, qué nos van a ayudar a tener herramientas para saber lo que es realmente una alimentación saludable. Los puntos más importantes que veremos son: Los conceptos básicos sobre la nutrición en las diferentes edades, maneras de poder alimentarse de manera saludable pero deliciosa e ideas sobre distintos platillos. Cuenta con 16 clases, 4 exámenes parciales y 1 examen final',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":9,"course_code":"nutricion_alimentacion","academy":"Academia de Salud y Bienestar","declared_classes":16}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Marketing Digital', 'Curso: Marketing Digital.
Academia: Academia de Marketing.
Cantidad informada por el manual: 16 clases.
En este diplomado lograremos desarrollar estrategias exitosas para comunicar de forma eficaz y potenciar tu negocio. En este curso aprenderás las principales áreas dentro del mundo digital: Redes Sociales, contenido, tácticas, métricas y herramientas web. Los puntos más importantes que veremos son: la diferencia entre marketing digital y marketing tradicional, introducción a las redes sociales, qué estrategias hay que tener en cuenta, cómo se miden las métricas en las redes y la planificación. Cuenta con 16 clases y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":10,"course_code":"marketing_digital","academy":"Academia de Marketing","declared_classes":16}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Community Manager', 'Curso: Community Manager.
Academia: Academia de Marketing.
Cantidad informada por el manual: 16 clases.
Aprenderemos a manejar, optimizar y administrar de forma profesional tus redes sociales: crear estrategias de Social Media, hacer campañas digitales, actuar en una crisis y medir el éxito de tu negocio online. Los puntos más importantes que veremos son: El marketing de contenidos, la planificación, estrategias y atención al cliente online, campañas digitales y cómo hacer el presupuesto. Cuenta con 16 clases, 15 actividades y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":10,"course_code":"community_manager","academy":"Academia de Marketing","declared_classes":16}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Especialista en Marketing', 'Curso: Especialista en Marketing.
Academia: Academia de Marketing.
Cantidad informada por el manual: 17 clases.
Al aprender marketing podrás analizar los mercados, mejorar la distribución y logística de tu emprendimiento, crear una campaña de publicidad y comunicación, posicionar tu marca y entender cuáles son las necesidades de tus clientes. Los puntos más importantes que veremos son: Conceptos generales del marketing, la planeación estratégica, investigación de mercados, ciclo de vida del producto, publicidad y promoción y relaciones públicas. Se compone de 17 clases, 7 ejercicios y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":10,"course_code":"especialista_marketing","academy":"Academia de Marketing","declared_classes":17}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Introducción al Ecommerce', 'Curso: Introducción al Ecommerce.
Academia: Academia de Marketing.
Cantidad informada por el manual: 8 clases.
En este diplomado brindaremos todas las herramientas necesarias para vender productos en internet, comenzando desde los fundamentos básicos, pasando por el desarrollo de un plan de acción con objetivos. Enseñaremos las diferentes plataformas y estrategias para atraer al público a tu sitio web, tanto gratuitas como pagas. Los puntos más importantes que veremos son: El contenido lo vamos a ver dividido en 5 segmentos, en primer lugar veremos la INTRODUCCIÓN AL ECOMMERCE donde aprenderemos las ventajas del ecommerce, porque es conveniente tener un sitio web, diferentes maneras de desarrollar una web de ecommerce, en segundo lugar CREANDO UN SITIO WEB brindaremos las diferentes herramientas para crear tu ecommerce, elección de presupuesto adecuado al tamaño de tu negocio, la estructura en tu web, aspectos legales, la logística y el diseño. En tercer lugar el PLANEAMIENTO ESTRATÉGICO veremos el plan de marketing, auditoria de la competencia, modelos de clientes, luego casi llegando al final en cuarto lugar veremos ATRAYENDO A CLIENTES en donde aprenderemos el marketing de contenidos, la creación de los mismos, anuncios en plataformas y programación de contenidos. Y por último MEDICIÓN Y OPTIMIZACIÓN donde veremos que es un KPI (indicador de calidad) y cómo debemos analizar los datos de nuestra web. Cuenta con 8 clases, 3 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":10,"course_code":"introduccion_ecommerce","academy":"Academia de Marketing","declared_classes":8}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Fotografía con Celulares para Tiendas Online', 'Curso: Fotografía con Celulares para Tiendas Online.
Academia: Academia de Marketing.
Cantidad informada por el manual: 20 clases.
En este curso vamos a ver cómo aprovechar al máximo la cámara de nuestro celular, técnicas de iluminación, conceptos de fotografía y exposición, edición y retoque de los productos, creación de videos promocionales y cómo aplicar todo a nuestra red social preferida para el impulso de nuestro negocio. Los puntos más importantes que veremos son: Lo vamos a ver divididos en dos segmentos, en primer lugar FOTOGRAFIA CON CELULAR en donde veremos una introducción a dispositivos móviles, como mejorar la calidad de imagen, controlar la luz y los tipos de iluminación, que se debe tomar en cuenta a la hora de fotografiar nuestro producto, el manejo de las sombras y la diferencia entre fondo blanco y negro y todos sus beneficios y el segundo segmento será de CREACION DE CONTENIDO Y EDICION DE FOTOGRAFIAS donde aprenderemos sobre las redes sociales, la edición y los retoques que podemos darle a nuestras imágenes con el celular, creación de fondos para nuestras fotografías, conceptos de videos, filmación, tomas y cortes, creación del feed para instagram y llegando al final el armado de nuestra tienda online. Cuenta con 20 clases, 3 ejercicios, 1 examen parcial y 1 examen final',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":11,"course_code":"fotografia_celulares_tiendas_online","academy":"Academia de Marketing","declared_classes":20}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Influencers y Creadores de Contenidos', 'Curso: Influencers y Creadores de Contenidos.
Academia: Academia de Marketing.
Cantidad informada por el manual: 20 clases.
En este diplomado veremos y te enseñaremos cómo lograr y crear tu propia comunidad, sobre temas que te gusten y apasionen, con contenidos originales y gran empatía en las diferentes redes sociales, logrando interactuar y estrechar lazos con los seguidores para poder convertirte en un verdadero influencer. Los puntos más importantes que veremos son: introducción a las redes sociales, el marketing de contenidos para influenciadores, cómo crear contenido, introducción a instagram, youtube y como monetizarlo, hashtag y estadísticas. Cuenta con 20 clases, 9 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":11,"course_code":"influencers_creadores_contenidos","academy":"Academia de Marketing","declared_classes":20}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Publicidad en Redes Sociales', 'Curso: Publicidad en Redes Sociales.
Academia: Academia de Marketing.
Cantidad informada por el manual: 10 clases.
Con este curso aprenderemos a hacer publicidad en Facebook e instagram y generar anuncios de forma eficiente en plataformas para público específico como twitter y linkedln. Los puntos más importantes que veremos son: Introducción a las redes sociales, marketing, creación de contenidos, estadísticas en diferentes redes sociales, como se debe monetizar tu trabajo y la interacción con diferentes marcas e influencers. Cuenta con 10 clases, 5 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":11,"course_code":"publicidad_redes_sociales","academy":"Academia de Marketing","declared_classes":10}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Maquillaje Profesional', 'Curso: Maquillaje Profesional.
Academia: Academia de Moda y Belleza.
Cantidad informada por el manual: 38 clases.
El curso plantea como meta específica lograr conocimientos para trabajar como maquillador profesional, reconociendo los materiales de trabajo, tipo de pieles, forma de rostros, gustos del cliente y asesoramientos necesarios en cada trabajo. Pudiendo realizar un maquillaje profesional y duradero. Cuenta con 38 clases, 20 exámenes parciales, 3 ejercicios y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":11,"course_code":"maquillaje_profesional","academy":"Academia de Moda y Belleza","declared_classes":38}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Uñas Gelificadas', 'Curso: Uñas Gelificadas.
Academia: Academia de Moda y Belleza.
Cantidad informada por el manual: 25 clases.
Incorporar conocimientos y habilidades propias de la construcción de uñas en gel en las manos. Acompañar y asesorar a cualquier persona que desee efectuar un cambio de imagen en sus manos. Saber evaluar los diferentes casos teniendo en cuenta la forma de las uñas, y la anatomía de las manos para realizar de la forma más estéticamente natural la construcción de las uñas en gel. Diferenciar las diferentes patologías en las uñas evaluando conscientemente lo que se ajusta a cada caso. Cuenta con 25 clases, 5 actividades, 9 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"course_code":"unas_gelificadas","academy":"Academia de Moda y Belleza","declared_classes":25}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Instalación y Configuración de Cámaras de Seguridad', 'Curso: Instalación y Configuración de Cámaras de Seguridad.
Academia: Academia de Oficios.
Cantidad informada por el manual: 12 clases.
En este diplomado le brindaremos a los participantes los conocimientos necesarios y técnicos, para la instalación y configuración de Cámaras de Seguridad en comercios, casas, galpones o empresas, permitiendo visualizarlas en diferentes componentes (TV, PC y/o Celulares). Incorporar toda la terminología correspondiente para manejarse en este rubro y aprender a manejar las diferentes herramientas que demanda este tipo de instalación. Cuenta con 12 clases y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"course_code":"camaras_seguridad","academy":"Academia de Oficios","declared_classes":12}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Instalación de Aires Acondicionados', 'Curso: Instalación de Aires Acondicionados.
Academia: Academia de Oficios.
Cantidad informada por el manual: 9 clases.
El propósito del curso de instalador es el de instruir a todas las personas a que puedan emprender las tareas de instalación y puesta en marcha de equipos de Aire Acondicionado. Cada usuario tiene intereses particulares sobre el equipo a instalar referentes a su ubicación y disposición de las unidades, necesidades a satisfacer, instalación de las cañerías, resultado y funcionamiento del equipo instalado. Pretendiendo un nivel de terminación adecuado. Cuenta con 9 clases y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"course_code":"aires_acondicionados","academy":"Academia de Oficios","declared_classes":9}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Energía Solar Fotovoltaica', 'Curso: Energía Solar Fotovoltaica.
Academia: Academia de Oficios.
Cantidad informada por el manual: 8 clases.
Conocer el componente más importante en las instalaciones fotovoltaicas, los módulos fotovoltaicos, únicos dispositivos capaces de convertir directamente la energía luminosa procedente del sol en energía eléctrica continua e introducirnos en la energía solar fotovoltaica, que es la transformación de la luz solar en energía. Cuenta con 8 clases, 4 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"course_code":"energia_solar_fotovoltaica","academy":"Academia de Oficios","declared_classes":8}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Armado y Reparación de PC', 'Curso: Armado y Reparación de PC.
Academia: Academia de Oficios.
Cantidad informada por el manual: 22 clases.
Este curso abarca el mantenimiento de computadoras de escritorio desde cero con casos reales otorgando las herramientas necesarias para que el futuro técnico sepa cuándo reparar y cuándo reemplazar los componentes dañados como también asesorar a sus clientes con las mejores soluciones a su equipamiento. Cuenta con 22 clases, 10 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":12,"course_code":"armado_reparacion_pc","academy":"Academia de Oficios","declared_classes":22}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Reparación de Celulares', 'Curso: Reparación de Celulares.
Academia: Academia de Oficios.
Cantidad informada por el manual: 20 clases.
Los objetivos de este curso son: lograr que el alumno conozca la evolución de la telefonía celular, hasta el desarrollo total de los Smartphone que tenemos en la actualidad, saber manipular distintas herramientas de medición, adquirir el conocimiento para poder realizar distintas reparaciones (tales como cambios de módulos, reparación de pines y de integrados de teléfonos celulares). Lograr manipular conceptos de programación, y aprender cómo reprogramar o proteger un teléfono celular, de distintas marcas. Este curso cuenta con 20 clases, 4 actividades, 5 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"course_code":"reparacion_celulares","academy":"Academia de Oficios","declared_classes":20}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Redes Informáticas', 'Curso: Redes Informáticas.
Academia: Academia de Oficios.
Cantidad informada por el manual: 16 clases.
Este curso te permitirá conocer el funcionamiento de las redes informáticas, y cada uno de los elementos y dispositivos que la componen. Entender las diferentes capas que interactúan para poder transmitir la información y distribuirla alrededor del mundo y saber: ● Estructurar la arquitectura de una red ● Determinar la funcionalidad de los dispositivos de red ● Comprender las capas de un modelo de red ● Conocer las diferencias entre los modelos de redes que existen. Este diplomado cuenta con 16 clases, 8 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"course_code":"redes_informaticas","academy":"Academia de Oficios","declared_classes":16}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Decoración de Interiores', 'Curso: Decoración de Interiores.
Academia: Academia de Emprendedores.
Cantidad informada por el manual: 33 clases.
Este curso invita a los participantes a formarse en el oficio de Decorador de Interiores, aprendiendo sus primeros pasos en el mundo del diseño y la decoración. Mostrándoles los inicios, tendencias, estilos, herramientas, materiales, consejos. Cuenta con 33 clases, 12 ejercicios, 7 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"course_code":"decoracion_de_interiores","academy":"Academia de Emprendedores","declared_classes":33}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Fotografía Profesional', 'Curso: Fotografía Profesional.
Academia: Academia de Emprendedores.
Cantidad informada por el manual: 41 clases.
Este curso está apuntado a todo aquel que quiera conocer desde cero el proceso fotográfico actual, con esto nos referimos al digital. En el momento que fue creado este contenido contamos con una enorme cantidad de dispositivos aptos para realizar fotografías. A lo largo del curso se verán contenidos y prácticas buscando que el alumno logré controlar los principales parámetros de fotografía, manejo de cámara y edición. Cuenta con 41 clases, 1 examen parcial y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"course_code":"fotografia_profesional","academy":"Academia de Emprendedores","declared_classes":41}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Organizador Profesional de Eventos Sociales', 'Curso: Organizador Profesional de Eventos Sociales.
Academia: Academia de Emprendedores.
Cantidad informada por el manual: 20 clases.
Durante estas clases virtuales, aprenderás conceptos, términos del rubro de eventos, para aplicar en el armado y desarrollo de tu empresa de eventos. Contiene material inspirador para trabajar en equipo. Este curso se destaca por brindar herramientas teóricas y prácticas, no solo para convertirte en un OPE, sino también para vender tus servicios, incluye clases especiales para potenciar tu emprendimiento en redes sociales. Este diplomado cuenta con 20 clases, 1 trabajo práctico, 5 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":13,"course_code":"organizador_eventos_sociales","academy":"Academia de Emprendedores","declared_classes":20}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Organización de Baby Shower', 'Curso: Organización de Baby Shower.
Academia: Academia de Emprendedores.
Cantidad informada por el manual: 21 clases.
Celebrar la vida es parte de la magia de un Organizador de Eventos de Baby Shower, trabajar en un momento tan especial como la dulce espera de un bebé es un momento de emociones para la familia como para todo el personal que trabaja en el evento. Destacar emociones nos sensibiliza como profesional y eso es clave en este tipo de festejo que tiene como fin festejar la llegada de un nuevo miembro al hogar.Este diplomado cuenta con 21 clases, 1 trabajo práctico, exámenes parciales y 1 examen parcial.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"course_code":"organizacion_baby_shower","academy":"Academia de Emprendedores","declared_classes":21}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Paisajismo y Jardinería', 'Curso: Paisajismo y Jardinería.
Academia: Academia de Emprendedores.
Cantidad informada por el manual: 23 clases.
El curso tiene como objetivo brindar al alumno todas las variedades que se le pueden presentar en el momento de intervenir en un paisaje natural, capacitarlo en el estudio y el reconocimiento del espacio exterior tales como jardines delanteros, traseros, terrazas, balcones y en el ámbito público en parques y plazas, aprendiendo a analizar los componentes naturales y materiales posibles a utilizar. También le aportará conocimientos varios sobre las especies vegetales, los cuidados que requieren y los estilos de diseño.Este diplomado cuenta con 23 clases, 7 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"course_code":"paisajismo_jardineria","academy":"Academia de Emprendedores","declared_classes":23}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Estrategias para Emprender', 'Curso: Estrategias para Emprender.
Academia: Academia de Emprendedores.
Cantidad informada por el manual: 20 clases.
En este curso proponemos claves fundamentales para emprender un negocio con éxito, a través de estrategias efectivas para no fallar en el intento. Emprender requiere inversión, tiempo, esfuerzo y sobre todo, mucha inteligencia a la hora de planificar. Los invitamos a adentrarse en el fascinante mundo del emprendedurismo para transformar el presente en un futuro mejor.Este diplomado cuenta con 20 clases, 6 exámenes parciales y 1 examen parcial',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"course_code":"estrategias_emprender","academy":"Academia de Emprendedores","declared_classes":20}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Instagram para Emprendedores', 'Curso: Instagram para Emprendedores.
Academia: Academia de Emprendedores.
Cantidad informada por el manual: 10 clases.
El curso está pensado para que los emprendedores puedan desarrollar sus negocios y consigan mayor visibilidad. Instagram es la red social más activa, que permite potenciar los emprendimientos con sus productos y servicios. Permite estar en el mapa de los usuarios que están cerca colocando la ubicación o seleccionando la etiqueta correcta. Este diplomado cuenta con 10 clases, 6 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"course_code":"instagram_emprendedores","academy":"Academia de Emprendedores","declared_classes":10}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Diseño Gráfico con Corel Draw', 'Curso: Diseño Gráfico con Corel Draw.
Academia: Academia de Diseño Informático.
Cantidad informada por el manual: 16 clases.
Es sumamente necesario entender la tarea de un diseñador gráfico y con el profesionalismo que debemos encarar nuestro trabajo para poder hacerlo de la mejor manera. Vamos a encontrar aquellos que opinen que nuestra tarea es la de “embellecer” una pieza gráfica, de rellenar espacios, de hacerlos atractivos y nuestra tarea va mucho más allá de eso. Este diplomado cuenta con 16 clases, 1 trabajo práctico integrador, 10 ejercicios y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"course_code":"diseno_corel_draw","academy":"Academia de Diseño Informático","declared_classes":16}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Diseño Gráfico con Photoshop', 'Curso: Diseño Gráfico con Photoshop.
Academia: Academia de Diseño Informático.
Cantidad informada por el manual: 16 clases.
Este diplomado cuenta con 16 clases, 8 ejercicios y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":14,"course_code":"diseno_photoshop","academy":"Academia de Diseño Informático","declared_classes":16}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Diseño Gráfico con Illustrator', 'Curso: Diseño Gráfico con Illustrator.
Academia: Academia de Diseño Informático.
Cantidad informada por el manual: 17 clases.
Este diplomado cuenta con 17 clases, 17 ejercicios, 6 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"course_code":"diseno_illustrator","academy":"Academia de Diseño Informático","declared_classes":17}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — AutoCAD orientado al Diseño de Interiores', 'Curso: AutoCAD orientado al Diseño de Interiores.
Academia: Academia de Diseño Informático.
Cantidad informada por el manual: 11 clases.
En este Curso de AutoCAD vamos a adquirir el conocimiento práctico y teórico para dominar las técnicas de dibujo en forma digital y realizar planos técnicos en dos dimensiones. El curso está apuntado a los alumnos de las áreas de decoración de interiores, diseños efímeros y diseño de mobiliario. Este diplomado cuenta con 11 clases y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"course_code":"autocad_interiores","academy":"Academia de Diseño Informático","declared_classes":11}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Excel Integral', 'Curso: Excel Integral.
Academia: Academia de Negocios.
Cantidad informada por el manual: 17 clases.
Recomendamos este curso, con el que aprenderá las herramientas elementales, diferente tipos de fórmulas y funciones, gráficos, resúmenes de información, entre otras tantas actividades que puede realizar con este programa. Este diplomado cuenta con 17 clases, 1 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"course_code":"excel_integral","academy":"Academia de Negocios","declared_classes":17}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Especialista en Ventas', 'Curso: Especialista en Ventas.
Academia: Academia de Negocios.
Cantidad informada por el manual: 16 clases.
A través de este curso obtendrás todas las aptitudes necesarias para poder optimizar tus recursos y potenciar tus ventas. Aprenderás diferentes técnicas de negociación, así como también a realizar un discurso asertivo. Veras todas las características de la escucha activa. Podrás convertir a tus consumidores en clientes con estrategias de fidelización.Este diplomado cuenta con 16 clases, 5 ejercicios, 1 trabajo práctico y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"course_code":"especialista_ventas","academy":"Academia de Negocios","declared_classes":16}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Coaching y Liderazgo', 'Curso: Coaching y Liderazgo.
Academia: Academia de Negocios.
Cantidad informada por el manual: 16 clases.
En este curso permitiremos desarrollar actitudes, capacidades y habilidades que posibiliten enfrentar adecuadamente los desafíos del mercado laboral, en especial a nivel gerencial. Reconocer las competencias conversacionales como factor clave para el incremento de la productividad. Desarrollar habilidades que permitan al alumno lograr relaciones laborales efectivas y realizar sus tareas cotidianas de forma más eficiente y eficaz. Incorporar el aprendizaje de una nueva visión que les permita expandir sus posibilidades de éxito.Este diplomado cuenta con 16 clases, 4 trabajos prácticos y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"course_code":"coaching_liderazgo","academy":"Academia de Negocios","declared_classes":16}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Comunicación Interna en Empresas', 'Curso: Comunicación Interna en Empresas.
Academia: Academia de Negocios.
Cantidad informada por el manual: 20 clases.
En este curso, brindaremos las estrategias necesarias para gestionar e integrar adecuadamente un equipo humano de una empresa. El objetivo es incrementar el vínculo cordial entre los empleados, a fin de aumentar su productividad y desempeño.Este diplomado cuenta con 20 clases, 6 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"course_code":"comunicacion_interna_empresas","academy":"Academia de Negocios","declared_classes":20}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Introducción a las Criptomonedas', 'Curso: Introducción a las Criptomonedas.
Academia: Academia de Negocios.
Cantidad informada por el manual: 21 clases.
El objetivo de este curso es lograr que el alumno se familiarice con los conceptos básicos del mundo de las criptomonedas. Es un curso introductorio, que no requiere conocimientos previos, y está apuntado a todos aquellos interesados en entender qué es y cómo funciona el mundo cripto. Repasaremos la historia de la criptografía y las principales monedas virtuales. Analizaremos en profundidad el Bitcoin y buscaremos entender cuál es el potencial que las criptomonedas tienen para cambiar para siempre la forma en la que utilizamos, ahorramos e invertimos nuestro dinero. Este diplomado cuenta con 21 clases, 3 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":15,"course_code":"introduccion_criptomonedas","academy":"Academia de Negocios","declared_classes":21}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Oratoria', 'Curso: Oratoria.
Academia: Academia Cultural.
Cantidad informada por el manual: 20 clases.
En este curso, analizaremos las claves de la oratoria, facilitando herramientas esenciales para lograr buenos resultados comunicaciones y alcanzar un feedback sin ruidos ni complicaciones con los interlocutores. Desde la postura frente al otro hasta la dicción y la pérdida del miedo a hablar en público, desarrollaremos un ABC imprescindible para que puedan convertirse en juiciosos oradores y, así, llegar a buen puerto en cualquier ámbito que se les presente. Este diplomado cuenta con 20 clases, 6 exámenes parciales, 2 ejercicios y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":16,"course_code":"oratoria","academy":"Academia Cultural","declared_classes":20}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Inglés 1', 'Curso: Inglés 1.
Academia: Academia Cultural.
Cantidad informada por el manual: 12 clases.
El objetivo de este curso es que el alumno adquiera conocimientos de inglés que perduren en el tiempo a través del aprendizaje y la lectura de materiales teóricos que pueda aplicar y apropiar en la práctica. Se trabajará en acercar al estudiante a la lengua de forma natural, se explicarán los conceptos básicos del idioma, se ayudará a estructurar conversaciones y comunicaciones escritas y orales simples pero efectivas, se motivará a cada persona a poner en práctica lo aprendido en producciones originales dentro y fuera del aula para comprender e interactuar con los hablantes nativos y no nativos.Este diplomado cuenta con 12 clases, 4 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":16,"course_code":"ingles_1","academy":"Academia Cultural","declared_classes":12}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Inglés 2', 'Curso: Inglés 2.
Academia: Academia Cultural.
Cantidad informada por el manual: 12 clases.
En este diplomado el alumno se adentrará en los modos, en cómo entablar una conversación y podrá aplicar todo lo aprendido. Este diplomado cuenta con 12 clases, 3 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":16,"course_code":"ingles_2","academy":"Academia Cultural","declared_classes":12}'::jsonb
  ),
(
    gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'offering',
    'Manual StudyX — Inglés 3', 'Curso: Inglés 3.
Academia: Academia Cultural.
Cantidad informada por el manual: 21 clases.
En este diplomado el alumno adquirirá conocimientos sobre gramática y vocabulario que le dará las herramientas necesarias para poder desenvolverse en los distintos contextos presentados en el curso, tales como en el aeropuerto, en una entrevista laboral, etc. Se brindará ayuda visual, audios, videos y diversas actividades que ayudarán al alumno a adquirir y practicar los temas presentados. La comunicación y el uso del inglés en la vida real son los principales tópicos en este curso.Este diplomado cuenta con 21 clases, 3 exámenes parciales y 1 examen final.',
    'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1","source_page":16,"course_code":"ingles_3","academy":"Academia Cultural","declared_classes":21}'::jsonb
  ),
(
  gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'business_profile',
  'Manual StudyX — Catálogo oficial', 'Catálogo oficial de StudyX según el manual definido por el propietario como fuente de verdad.
Total explícito: 40 cursos en 9 academias.
Academia Gastronómica: Introducción al Vino, la Cata y el Maridaje; Introducción al Catering; Sushi para Principiantes.
Academia de Salud y Bienestar: Entrenamiento Funcional; Nutrición y Alimentación Saludable.
Academia de Marketing: Marketing Digital; Community Manager; Especialista en Marketing; Introducción al Ecommerce; Fotografía con Celulares para Tiendas Online; Influencers y Creadores de Contenidos; Publicidad en Redes Sociales.
Academia de Moda y Belleza: Maquillaje Profesional; Uñas Gelificadas.
Academia de Oficios: Instalación y Configuración de Cámaras de Seguridad; Instalación de Aires Acondicionados; Energía Solar Fotovoltaica; Armado y Reparación de PC; Reparación de Celulares; Redes Informáticas.
Academia de Emprendedores: Decoración de Interiores; Fotografía Profesional; Organizador Profesional de Eventos Sociales; Organización de Baby Shower; Paisajismo y Jardinería; Estrategias para Emprender; Instagram para Emprendedores.
Academia de Diseño Informático: Diseño Gráfico con Corel Draw; Diseño Gráfico con Photoshop; Diseño Gráfico con Illustrator; AutoCAD orientado al Diseño de Interiores.
Academia de Negocios: Excel Integral; Especialista en Ventas; Coaching y Liderazgo; Comunicación Interna en Empresas; Introducción a las Criptomonedas.
Academia Cultural: Oratoria; Inglés 1; Inglés 2; Inglés 3.',
  'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1"}'::jsonb
),
(
  gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'process',
  'Manual StudyX — Uso de la plataforma', 'El manual incluye orientación visual sobre el uso de la plataforma StudyX.
Temas cubiertos: Ingreso al campus; Campus por dentro; Clases en vivo y cómo acceder; Calendario de eventos; Insignias; Todos los cursos; Ingreso a las clases; Consultas al profesor paso a paso; Cómo ingresar a una clase y enviar ejercicios.
No contiene horarios concretos de clases ni fechas de inicio.',
  'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1"}'::jsonb
),
(
  gen_random_uuid(), 'b0000000-0000-4000-8000-000000000001', 'policy',
  'Manual StudyX — Ambigüedades que requieren confirmación', 'Ceremonial y Protocolo: Se menciona una sola vez en la página 16 como parte de Academia Cultural, pero no aparece en el catálogo inicial ni tiene descripción o cantidad de clases. Regla comercial: no_ofrecer_hasta_confirmacion.',
  'active', 1, '{"canonical_source":"studyx_manual_1","source_file":"MANUAL CAPACITACION STUDYX 1.docx.pdf","source_sha256":"47a08b918cde15b8e2da6c3dc24fab6a584801611032665585738a052f1732a1"}'::jsonb
)
ON CONFLICT (workspace_id, title, version) DO UPDATE SET
  source_type = EXCLUDED.source_type,
  content = EXCLUDED.content,
  status = EXCLUDED.status,
  metadata = EXCLUDED.metadata,
  updated_at = now();

COMMIT;
